# Plot QTL mapping results generated by the map.qtls.combined.R script.
library(lattice)
library(qtl)

# SCRIPT PARAMETERS
# -----------------
threshold <- 0.05  # Significance threshold.
ymax      <- 10    # Height of vertical axis.

# Load the QTL mapping results *with* sex as an interactive covariate.
load("gwscan.combined.sex.RData")
gwscan.qtl.sex <- gwscan.qtl
gwscan.rel.sex <- gwscan.rel
perms.qtl.sex  <- perms.qtl

# Load the QTL mapping results *without* sex as an interactive covariate.
load("gwscan.combined.RData")

# Show QTL mapping results for these phenotypes, and on these chromosomes.
phenotypes <- c("TA","EDL","gastroc","soleus")
phenotypes <- phenotypes[3:4]

# PLOT QTL MAPPING RESULTS
# ------------------------
n <- length(phenotypes)
trellis.device(width = 11,height = 3.5,title = "QTL mapping results")
par(ps = 11,font.lab = 1,font.main = 1,mai = c(0.3,0.3,0.2,0.1))
layout(matrix(1:(3*n),nrow = 3,ncol = n))

# Repeat for each phenotype.
for (i in 1:n) {
  phenotype <- phenotypes[i]

  # PLOT RESULTS FROM F8 DATA
  # -------------------------
  # Plot the QTL mapping results from QTLRel in the F8 cross, with sex
  # as an interactive covariate.
  plot(gwscan.rel.sex$F8[[phenotype]],lodcolumn = 1,incl.markers = FALSE,
       bandcol = "gray",col = "dodgerblue",lwd = 2,ylim = c(0,ymax),gap = 0,
       xlab = "",ylab = "",main = paste(phenotype,"(F8 sample)"))

  # Plot the QTL mapping results from QTLRel in the F8 cross, without
  # sex as an interactive covariate.
  plot(gwscan.rel$F8[[phenotype]],lodcolumn = 1,lwd = 2,col = "black",
       incl.markers = FALSE,bandcol = "gray",ylim = c(0,ymax),gap = 0,
       add = TRUE)
  
  # Add the significance thresholds to the plot.
  add.threshold(gwscan.qtl.sex$F8,perms = perms.qtl.sex$F8,alpha = threshold,
                gap = 0,lodcolumn = i,col = "dodgerblue",lty = "dotted",
                lwd = 1)
  add.threshold(gwscan.qtl$F8,perms = perms.qtl$F8,alpha = threshold,gap = 0,
                lodcolumn = i,col = "black",lty = "dotted",lwd = 1)
  
  # PLOT RESULTS FROM F9-F13 DATA
  # -----------------------------
  # Plot the QTL mapping results from QTLRel in the F9-F13 cohort,
  # with sex as an interactive covariate.
  plot(gwscan.rel.sex[["F9-F13"]][[phenotype]],lodcolumn = 1,bandcol = "gray",
       incl.markers = FALSE,col = "dodgerblue",ylim = c(0,ymax),gap = 0,
       xlab = "",ylab = "",lwd = 2,main = paste(phenotype,"(F9-F13 sample)"))

  # Plot the QTL mapping results from QTL in the F9-F13 cohort,
  # without sex as an interactive covariate.
  plot(gwscan.rel[["F9-F13"]][[phenotype]],lodcolumn = 1,bandcol = "gray",
       incl.markers = FALSE,col = "black",ylim = c(0,ymax),gap = 0,lwd = 2,
       add = TRUE)
  
  # Add the significance thresholds to the plot.
  add.threshold(gwscan.qtl.sex[["F9-F13"]],perms = perms.qtl.sex[["F9-F13"]],
                alpha = threshold,gap = 0,lodcolumn = i,lwd = 1,
                col = "dodgerblue",lty = "dotted")
  add.threshold(gwscan.qtl[["F9-F13"]],perms = perms.qtl[["F9-F13"]],
                alpha = threshold,gap = 0,lodcolumn = i,lwd = 1,
                col = "black",lty = "dotted")
  
  # PLOT RESULTS FROM COMBINED DATA
  # -------------------------------
  # Plot the QTL mapping results from QTLRel in the combined sample,
  # with sex as an interactive covariate.
  plot(gwscan.rel.sex$combined[[phenotype]],lodcolumn = 1,bandcol = "gray",
       incl.markers = FALSE,col = "dodgerblue",ylim = c(0,ymax),gap = 0,
       xlab = "",ylab = "",lwd = 2,main = paste(phenotype,"(combined sample)"))

  # Plot the QTL mapping results from QTLRel in the combined sample,
  # without sex as an interactive covariate.
  plot(gwscan.rel$combined[[phenotype]],lodcolumn = 1,bandcol = "gray",
       lwd = 2,incl.markers = FALSE,col = "black",ylim = c(0,ymax),
       gap = 0,add = TRUE)
  
  # Add the significance thresholds to the plot.
  add.threshold(gwscan.qtl.sex$combined,perms = perms.qtl.sex$combined,
                alpha = threshold,gap = 0,lodcolumn = i,lwd = 1,
                col = "dodgerblue",lty = "dotted")
  add.threshold(gwscan.qtl$combined,perms = perms.qtl$combined,
                alpha = threshold,gap = 0,lodcolumn = i,lwd = 1,
                col = "black",lty = "dotted")
}
